### ISSUE TITLE
Calibration ... ongoing

### ISSUE THREAD

**Issue by marmitetype** [HCI-Lab-Saarland/MultiTouchKitUI#1]
Hi there, 
I am new to using the MultiTouchKitUI and I am wondering if you have any suggestions to troubleshoot if the processing is endlessly calibrating? For reference, I am using an arduino uno, and running processing 3.5.4 on Mac OS 11.5.2. (processing 4 didn't cooperate with the open cv processing library.) I tried both the 1.2.3 release examples, and the MTK_example from the original release. I know that the sensor is working because I can see signal in the serial plotter for Arduino. When I uncomment the section to reveal calibration values, rawvalues, baseline, and values all report 0:0 (see attached.) 
![Screen Shot 2021-11-26 at 10 42 21 AM](https://user-images.githubusercontent.com/95100694/143620660-e7e9cddd-3974-472c-90e9-db58050742c0.png)

Thank you for any help you can provide with this

**Comment by marmitetype** [comment]
Nevermind! I found a loose connection. Thanks anyway

**Comment by raffdav98** [comment]
Hi, how did you resolve this issue? i have the same problem

**Comment by raffdav98** [comment]
> Nevermind! I found a loose connection. Thanks anyway

hiii how have you solve this issue? I'm in the same situation
